#!/usr/bin/env bash
# Zero-downtime (web) restart / slot switch for BusyProxy behind nginx.
#
# Flow:
#   1. Start NEW slot on the idle port (8080 ↔ 8081)
#   2. Health-check the new process
#   3. Point nginx upstream at the new port + reload (no full nginx restart)
#   4. Stop the OLD slot
#
# Website stays up. Phone tunnels may briefly reconnect when the old process exits
# (edge ports 18080/11080 hand off; new process retries bind).
#
# Usage (on the droplet):
#   /opt/busyproxy/scripts/zero-downtime-restart.sh
#   /opt/busyproxy/scripts/zero-downtime-restart.sh --status
#   /opt/busyproxy/scripts/zero-downtime-restart.sh --migrate   # first-time from busyproxy.service
#
set -euo pipefail

STATE_DIR="${STATE_DIR:-/var/lib/busyproxy}"
ACTIVE_FILE="$STATE_DIR/active_port"
UPSTREAM_CONF="${UPSTREAM_CONF:-/etc/nginx/conf.d/busyproxy-upstream.conf}"
PORT_A=8080
PORT_B=8081
HEALTH_HOST="${HEALTH_HOST:-busyproxy.net}"
MAX_WAIT="${MAX_WAIT:-60}"

mkdir -p "$STATE_DIR"

log() { echo "[zd-restart] $*"; }
die() { echo "[zd-restart] ERROR: $*" >&2; exit 1; }

active_port() {
  if [[ -f "$ACTIVE_FILE" ]]; then
    cat "$ACTIVE_FILE"
  elif systemctl is-active --quiet busyproxy@8080 2>/dev/null; then
    echo 8080
  elif systemctl is-active --quiet busyproxy@8081 2>/dev/null; then
    echo 8081
  elif systemctl is-active --quiet busyproxy 2>/dev/null; then
    echo 8080
  else
    echo 8080
  fi
}

idle_port() {
  local a
  a=$(active_port)
  if [[ "$a" == "$PORT_A" ]]; then echo "$PORT_B"; else echo "$PORT_A"; fi
}

health() {
  local port="$1"
  curl -sf -o /dev/null --max-time 3 \
    -H "Host: ${HEALTH_HOST}" \
    "http://127.0.0.1:${port}/"
}

wait_healthy() {
  local port="$1"
  local i
  for i in $(seq 1 "$MAX_WAIT"); do
    if health "$port"; then
      log "slot :${port} healthy"
      return 0
    fi
    sleep 1
  done
  return 1
}

write_upstream() {
  local port="$1"
  cat >"$UPSTREAM_CONF" <<EOF
# Auto-generated by zero-downtime-restart.sh — active slot :${port}
upstream busyproxy_app {
  server 127.0.0.1:${port};
  keepalive 32;
}
EOF
  nginx -t
  systemctl reload nginx
  log "nginx upstream → 127.0.0.1:${port}"
}

cmd_status() {
  local a
  a=$(active_port)
  echo "active_port_file: $(cat "$ACTIVE_FILE" 2>/dev/null || echo '(none)')"
  echo "active_port:      $a"
  echo "idle_port:        $(idle_port)"
  echo "upstream:         $UPSTREAM_CONF"
  [[ -f "$UPSTREAM_CONF" ]] && grep -E 'server 127' "$UPSTREAM_CONF" || true
  systemctl is-active busyproxy 2>/dev/null && echo "legacy busyproxy: active" || echo "legacy busyproxy: inactive"
  systemctl is-active "busyproxy@${PORT_A}" 2>/dev/null && echo "busyproxy@${PORT_A}: active" || echo "busyproxy@${PORT_A}: inactive"
  systemctl is-active "busyproxy@${PORT_B}" 2>/dev/null && echo "busyproxy@${PORT_B}: active" || echo "busyproxy@${PORT_B}: inactive"
  health "$a" && echo "health :${a}: OK" || echo "health :${a}: FAIL"
  ss -lntp 2>/dev/null | grep -E ":${PORT_A}|:${PORT_B}|:18080|:11080" || true
}

# First-time: install units, move from busyproxy.service → busyproxy@8080
cmd_migrate() {
  log "migrate → blue/green slots"
  install -m 644 /opt/busyproxy/deploy/busyproxy@.service /etc/systemd/system/busyproxy@.service
  # Ensure conf.d upstream exists and site uses it
  if [[ ! -f "$UPSTREAM_CONF" ]]; then
    write_upstream 8080
  fi
  # Patch site to use upstream if still hard-coded to :8080
  if grep -q '127.0.0.1:8080' /etc/nginx/sites-enabled/busyproxy 2>/dev/null; then
    log "rewriting sites-enabled/busyproxy to use upstream busyproxy_app"
    sed -i 's|http://127.0.0.1:8080|http://busyproxy_app|g' /etc/nginx/sites-enabled/busyproxy
    nginx -t && systemctl reload nginx
  fi
  systemctl daemon-reload

  # Prefer keeping current process if already on 8080
  if systemctl is-active --quiet busyproxy 2>/dev/null; then
    log "legacy unit running — start @8080 then stop legacy"
    # If legacy holds 8080, @8080 cannot bind — stop legacy first only after @8081?
    # Safer: mark active 8080, ensure upstream 8080, stop legacy and start @8080 quickly
    echo 8080 >"$ACTIVE_FILE"
    write_upstream 8080
    systemctl stop busyproxy || true
    systemctl disable busyproxy || true
    systemctl enable "busyproxy@8080"
    systemctl start "busyproxy@8080"
    wait_healthy 8080 || die "migrate health failed on :8080"
    log "migrate complete — use zero-downtime-restart.sh for future restarts"
    return 0
  fi

  systemctl enable "busyproxy@8080"
  systemctl start "busyproxy@8080" || true
  echo 8080 >"$ACTIVE_FILE"
  write_upstream 8080
  wait_healthy 8080 || die "migrate health failed"
  log "migrate complete"
}

cmd_switch() {
  local active next
  active=$(active_port)
  next=$(idle_port)
  log "switch ${active} → ${next}"

  # Ensure template unit installed
  if [[ ! -f /etc/systemd/system/busyproxy@.service ]]; then
    install -m 644 /opt/busyproxy/deploy/busyproxy@.service /etc/systemd/system/busyproxy@.service
    systemctl daemon-reload
  fi

  # Disable legacy one-shot unit if present
  if systemctl is-active --quiet busyproxy 2>/dev/null; then
    log "legacy busyproxy.service still active — run --migrate first"
    die "run: $0 --migrate"
  fi

  # Start next slot (code already on disk under /opt/busyproxy)
  systemctl reset-failed "busyproxy@${next}" 2>/dev/null || true
  systemctl start "busyproxy@${next}"
  if ! wait_healthy "$next"; then
    log "new slot unhealthy — leaving active :${active}, stopping failed :${next}"
    systemctl stop "busyproxy@${next}" || true
    die "health check failed on :${next}"
  fi

  # Flip nginx (website now served by next)
  write_upstream "$next"
  echo "$next" >"$ACTIVE_FILE"

  # Brief settle so nginx workers pick upstream
  sleep 1
  health "$next" || die "post-switch health failed"

  # Drain old slot
  if systemctl is-active --quiet "busyproxy@${active}" 2>/dev/null; then
    log "stopping old slot :${active}"
    systemctl stop "busyproxy@${active}" || true
  fi

  log "done — active :${next} (old :${active} stopped)"
  cmd_status
}

case "${1:-}" in
  --status|status) cmd_status ;;
  --migrate|migrate) cmd_migrate ;;
  --switch|switch|"") cmd_switch ;;
  -h|--help|help)
    sed -n '2,20p' "$0" | sed 's/^# \?//'
    ;;
  *)
    die "unknown arg: $1 (use --status | --migrate | --switch)"
    ;;
esac
