/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as MobileStripeReturnRouteImport } from './routes/mobile.stripe-return'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalSectionRouteImport } from './routes/portal.$section'
import { Route as PortalDevicesDeviceIdRouteImport } from './routes/portal.devices.$deviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileStripeReturnRoute = MobileStripeReturnRouteImport.update({
  id: '/mobile/stripe-return',
  path: '/mobile/stripe-return',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSectionRoute = PortalSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDevicesDeviceIdRoute = PortalDevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/docs': typeof DocsRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/mobile/stripe-return': typeof MobileStripeReturnRoute
  '/portal/$section': typeof PortalSectionRoute
  '/portal/devices/$deviceId': typeof PortalDevicesDeviceIdRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/mobile/stripe-return': typeof MobileStripeReturnRoute
  '/portal/$section': typeof PortalSectionRoute
  '/portal/devices/$deviceId': typeof PortalDevicesDeviceIdRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/docs': typeof DocsRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/mobile/stripe-return': typeof MobileStripeReturnRoute
  '/portal/$section': typeof PortalSectionRoute
  '/portal/devices/$deviceId': typeof PortalDevicesDeviceIdRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deletion'
    | '/admin'
    | '/app'
    | '/dashboard'
    | '/design'
    | '/docs'
    | '/portal'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/mobile/stripe-return'
    | '/portal/$section'
    | '/portal/devices/$deviceId'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deletion'
    | '/admin'
    | '/app'
    | '/dashboard'
    | '/design'
    | '/docs'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/mobile/stripe-return'
    | '/portal/$section'
    | '/portal/devices/$deviceId'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/account-deletion'
    | '/admin'
    | '/app'
    | '/dashboard'
    | '/design'
    | '/docs'
    | '/portal'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/mobile/stripe-return'
    | '/portal/$section'
    | '/portal/devices/$deviceId'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDeletionRoute: typeof AccountDeletionRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  DashboardRoute: typeof DashboardRoute
  DesignRoute: typeof DesignRoute
  DocsRoute: typeof DocsRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  MobileStripeReturnRoute: typeof MobileStripeReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/stripe-return': {
      id: '/mobile/stripe-return'
      path: '/mobile/stripe-return'
      fullPath: '/mobile/stripe-return'
      preLoaderRoute: typeof MobileStripeReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/$section': {
      id: '/portal/$section'
      path: '/$section'
      fullPath: '/portal/$section'
      preLoaderRoute: typeof PortalSectionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/devices/$deviceId': {
      id: '/portal/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/portal/devices/$deviceId'
      preLoaderRoute: typeof PortalDevicesDeviceIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalDevicesDeviceIdRoute: typeof PortalDevicesDeviceIdRoute
  PortalSectionRoute: typeof PortalSectionRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDevicesDeviceIdRoute: PortalDevicesDeviceIdRoute,
  PortalSectionRoute: PortalSectionRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDeletionRoute: AccountDeletionRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  DashboardRoute: DashboardRoute,
  DesignRoute: DesignRoute,
  DocsRoute: DocsRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  MobileStripeReturnRoute: MobileStripeReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
